// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"infra-kit/apps/iam/ent/authority"
	"infra-kit/apps/iam/ent/group"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorityCreate is the builder for creating a Authority entity.
type AuthorityCreate struct {
	config
	mutation *AuthorityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (ac *AuthorityCreate) SetCode(s string) *AuthorityCreate {
	ac.mutation.SetCode(s)
	return ac
}

// SetName sets the "name" field.
func (ac *AuthorityCreate) SetName(s string) *AuthorityCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetCtime sets the "ctime" field.
func (ac *AuthorityCreate) SetCtime(t time.Time) *AuthorityCreate {
	ac.mutation.SetCtime(t)
	return ac
}

// SetMtime sets the "mtime" field.
func (ac *AuthorityCreate) SetMtime(t time.Time) *AuthorityCreate {
	ac.mutation.SetMtime(t)
	return ac
}

// SetID sets the "id" field.
func (ac *AuthorityCreate) SetID(s string) *AuthorityCreate {
	ac.mutation.SetID(s)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *AuthorityCreate) SetNillableID(s *string) *AuthorityCreate {
	if s != nil {
		ac.SetID(*s)
	}
	return ac
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (ac *AuthorityCreate) AddGroupIDs(ids ...string) *AuthorityCreate {
	ac.mutation.AddGroupIDs(ids...)
	return ac
}

// AddGroups adds the "groups" edges to the Group entity.
func (ac *AuthorityCreate) AddGroups(g ...*Group) *AuthorityCreate {
	ids := make([]string, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return ac.AddGroupIDs(ids...)
}

// Mutation returns the AuthorityMutation object of the builder.
func (ac *AuthorityCreate) Mutation() *AuthorityMutation {
	return ac.mutation
}

// Save creates the Authority in the database.
func (ac *AuthorityCreate) Save(ctx context.Context) (*Authority, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthorityCreate) SaveX(ctx context.Context) *Authority {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthorityCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthorityCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AuthorityCreate) defaults() {
	if _, ok := ac.mutation.ID(); !ok {
		v := authority.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthorityCreate) check() error {
	if _, ok := ac.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Authority.code"`)}
	}
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Authority.name"`)}
	}
	if _, ok := ac.mutation.Ctime(); !ok {
		return &ValidationError{Name: "ctime", err: errors.New(`ent: missing required field "Authority.ctime"`)}
	}
	if _, ok := ac.mutation.Mtime(); !ok {
		return &ValidationError{Name: "mtime", err: errors.New(`ent: missing required field "Authority.mtime"`)}
	}
	return nil
}

func (ac *AuthorityCreate) sqlSave(ctx context.Context) (*Authority, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Authority.ID type: %T", _spec.ID.Value)
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthorityCreate) createSpec() (*Authority, *sqlgraph.CreateSpec) {
	var (
		_node = &Authority{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(authority.Table, sqlgraph.NewFieldSpec(authority.FieldID, field.TypeString))
	)
	_spec.OnConflict = ac.conflict
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Code(); ok {
		_spec.SetField(authority.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(authority.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.Ctime(); ok {
		_spec.SetField(authority.FieldCtime, field.TypeTime, value)
		_node.Ctime = value
	}
	if value, ok := ac.mutation.Mtime(); ok {
		_spec.SetField(authority.FieldMtime, field.TypeTime, value)
		_node.Mtime = value
	}
	if nodes := ac.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   authority.GroupsTable,
			Columns: authority.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Authority.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthorityUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (ac *AuthorityCreate) OnConflict(opts ...sql.ConflictOption) *AuthorityUpsertOne {
	ac.conflict = opts
	return &AuthorityUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Authority.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AuthorityCreate) OnConflictColumns(columns ...string) *AuthorityUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AuthorityUpsertOne{
		create: ac,
	}
}

type (
	// AuthorityUpsertOne is the builder for "upsert"-ing
	//  one Authority node.
	AuthorityUpsertOne struct {
		create *AuthorityCreate
	}

	// AuthorityUpsert is the "OnConflict" setter.
	AuthorityUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *AuthorityUpsert) SetCode(v string) *AuthorityUpsert {
	u.Set(authority.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AuthorityUpsert) UpdateCode() *AuthorityUpsert {
	u.SetExcluded(authority.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *AuthorityUpsert) SetName(v string) *AuthorityUpsert {
	u.Set(authority.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AuthorityUpsert) UpdateName() *AuthorityUpsert {
	u.SetExcluded(authority.FieldName)
	return u
}

// SetCtime sets the "ctime" field.
func (u *AuthorityUpsert) SetCtime(v time.Time) *AuthorityUpsert {
	u.Set(authority.FieldCtime, v)
	return u
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *AuthorityUpsert) UpdateCtime() *AuthorityUpsert {
	u.SetExcluded(authority.FieldCtime)
	return u
}

// SetMtime sets the "mtime" field.
func (u *AuthorityUpsert) SetMtime(v time.Time) *AuthorityUpsert {
	u.Set(authority.FieldMtime, v)
	return u
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *AuthorityUpsert) UpdateMtime() *AuthorityUpsert {
	u.SetExcluded(authority.FieldMtime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Authority.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authority.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthorityUpsertOne) UpdateNewValues() *AuthorityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authority.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Authority.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthorityUpsertOne) Ignore() *AuthorityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthorityUpsertOne) DoNothing() *AuthorityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthorityCreate.OnConflict
// documentation for more info.
func (u *AuthorityUpsertOne) Update(set func(*AuthorityUpsert)) *AuthorityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthorityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *AuthorityUpsertOne) SetCode(v string) *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AuthorityUpsertOne) UpdateCode() *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AuthorityUpsertOne) SetName(v string) *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AuthorityUpsertOne) UpdateName() *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateName()
	})
}

// SetCtime sets the "ctime" field.
func (u *AuthorityUpsertOne) SetCtime(v time.Time) *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetCtime(v)
	})
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *AuthorityUpsertOne) UpdateCtime() *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateCtime()
	})
}

// SetMtime sets the "mtime" field.
func (u *AuthorityUpsertOne) SetMtime(v time.Time) *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *AuthorityUpsertOne) UpdateMtime() *AuthorityUpsertOne {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateMtime()
	})
}

// Exec executes the query.
func (u *AuthorityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthorityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthorityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthorityUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthorityUpsertOne.ID is not supported by MySQL driver. Use AuthorityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthorityUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthorityCreateBulk is the builder for creating many Authority entities in bulk.
type AuthorityCreateBulk struct {
	config
	err      error
	builders []*AuthorityCreate
	conflict []sql.ConflictOption
}

// Save creates the Authority entities in the database.
func (acb *AuthorityCreateBulk) Save(ctx context.Context) ([]*Authority, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Authority, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthorityCreateBulk) SaveX(ctx context.Context) []*Authority {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthorityCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthorityCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Authority.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthorityUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (acb *AuthorityCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthorityUpsertBulk {
	acb.conflict = opts
	return &AuthorityUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Authority.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AuthorityCreateBulk) OnConflictColumns(columns ...string) *AuthorityUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AuthorityUpsertBulk{
		create: acb,
	}
}

// AuthorityUpsertBulk is the builder for "upsert"-ing
// a bulk of Authority nodes.
type AuthorityUpsertBulk struct {
	create *AuthorityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Authority.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authority.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthorityUpsertBulk) UpdateNewValues() *AuthorityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authority.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Authority.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthorityUpsertBulk) Ignore() *AuthorityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthorityUpsertBulk) DoNothing() *AuthorityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthorityCreateBulk.OnConflict
// documentation for more info.
func (u *AuthorityUpsertBulk) Update(set func(*AuthorityUpsert)) *AuthorityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthorityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *AuthorityUpsertBulk) SetCode(v string) *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AuthorityUpsertBulk) UpdateCode() *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AuthorityUpsertBulk) SetName(v string) *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AuthorityUpsertBulk) UpdateName() *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateName()
	})
}

// SetCtime sets the "ctime" field.
func (u *AuthorityUpsertBulk) SetCtime(v time.Time) *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetCtime(v)
	})
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *AuthorityUpsertBulk) UpdateCtime() *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateCtime()
	})
}

// SetMtime sets the "mtime" field.
func (u *AuthorityUpsertBulk) SetMtime(v time.Time) *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *AuthorityUpsertBulk) UpdateMtime() *AuthorityUpsertBulk {
	return u.Update(func(s *AuthorityUpsert) {
		s.UpdateMtime()
	})
}

// Exec executes the query.
func (u *AuthorityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthorityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthorityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthorityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
