// Code generated by ent, DO NOT EDIT.

package ent

import (
	"infra-kit/apps/iam/ent/authority"
	"infra-kit/apps/iam/ent/credential"
	"infra-kit/apps/iam/ent/group"
	"infra-kit/apps/iam/ent/namespace"
	"infra-kit/apps/iam/ent/org"
	"infra-kit/apps/iam/ent/schema"
	"infra-kit/apps/iam/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authorityFields := schema.Authority{}.Fields()
	_ = authorityFields
	// authorityDescID is the schema descriptor for id field.
	authorityDescID := authorityFields[0].Descriptor()
	// authority.DefaultID holds the default value on creation for the id field.
	authority.DefaultID = authorityDescID.Default.(func() string)
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescID is the schema descriptor for id field.
	credentialDescID := credentialFields[0].Descriptor()
	// credential.DefaultID holds the default value on creation for the id field.
	credential.DefaultID = credentialDescID.Default.(func() string)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() string)
	namespaceFields := schema.Namespace{}.Fields()
	_ = namespaceFields
	// namespaceDescID is the schema descriptor for id field.
	namespaceDescID := namespaceFields[0].Descriptor()
	// namespace.DefaultID holds the default value on creation for the id field.
	namespace.DefaultID = namespaceDescID.Default.(func() string)
	orgFields := schema.Org{}.Fields()
	_ = orgFields
	// orgDescID is the schema descriptor for id field.
	orgDescID := orgFields[0].Descriptor()
	// org.DefaultID holds the default value on creation for the id field.
	org.DefaultID = orgDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
