// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authority is the predicate function for authority builders.
type Authority func(*sql.Selector)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Namespace is the predicate function for namespace builders.
type Namespace func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
